apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: argocd
  namespace: argocd
spec:
  secretName: argocd-tls
  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer
  commonName: "argocd.example.com"
  dnsNames:
    - "argocd.example.com"