commonLabels:
  team: infrastructure

resources:
  - namespace.yaml
  - https://raw.githubusercontent.com/argoproj/argo-cd/v2.5.7/manifests/install.yaml
  - ingress.yaml
  - certificate.yaml

patchesStrategicMerge:
  - patch-config.yaml