apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name:  gitea-cert
  namespace: gitea
spec:
  secretName: gitea-tls
  issuerRef:
    name: theClusterIssuer
    kind: ClusterIssuer
  commonName: "example.com"
  dnsNames:
    - "example.com"