persistence:
  enabled: true
  existingClaim:
  size: 10Gi
  accessModes:
    - ReadWriteOnce
  labels: {}
  annotations: {}
  storageClass: longhorn
  subPath:

gitea:
  admin:
    existingSecret: gitea-admin-secret
  metrics:
    enabled: enabled
    serviceMonitor:
      enabled: true
      additionalLabels:
        metrics: enabled

postgresql:
  enabled: false