apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: vclusters
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: Sprint service applications
  sourceRepos:
    - '*'
  destinations:
  - namespace: '*'
    server: https://kubernetes.default.svc
    name: in-cluster
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'