apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: longhorn
  namespace: longhorn-system
  annotations:
    kubernetes.io/ingress.class: traefik-external
spec:
  entryPoints:
  - websecure
  routes:
  - kind: Rule
    match: Host(`longhorn.infra.sprint.luchtenberg.eu`)
    services:
    - name: longhorn-frontend
      port: 80
  tls:
    secretName: longhorn-infra-sprint-luchtenberg-eu-production-tls
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: longhorn-infra-sprint-luchtenberg-eu
  namespace: longhorn-system
spec:
  secretName: longhorn-infra-sprint-luchtenberg-eu-production-tls
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: "longhorn.infra.sprint.luchtenberg.eu"
  dnsNames:
    - "longhorn.infra.sprint.luchtenberg.eu"