apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: gitea-db-secret
  namespace: database-infra
spec:
  encryptedData:
    password: AgACC8bsASN1XN9Oa+bqvqaGMH4lf4nEGWd7rNa5GbcJAEky0P9RaJ0+5Xc1zGGILX9i3xZnZKJI4kZpK2Ouj104b4wmmjzGl3agLGuzQZpNE/Mhc/6Fu8OQLi2UveOIOMsC3MGOiC4TLV00uG7+FG54UBAcqN5Q3QxuCC4KJCOb7fpdASLUfOgNBzhv2knWve/bp8lspBgM1zoYmoZm0FD/Hwc7qVRY/3WfDHHR1Is0Yr6rWd468CQdaLuRgZ4gYjF+x4J3vqbWqra2BZ8Bv1Jxg1ZPf81BrXB/K/DYfHL2ycsOHrZK8iBhRwxhvQfxjo40UAlDkWpBlC82sS095QKYUZQvq4QWYSZ6afpaY2Vyy7pfQpwLp7wkVVbYiKfHi4bw5zSymBhjCFmnOO53ILaDIUxqIW87MG2hOSoiADUzml6+ItmKvokmIV5wiUcNokMKTe6wFto8H+VKNFh2pCxFxcwXTAJenwnqxaWb4ojf9uL2gBxyC3GElQlIFBsGjC83yLRczIjA6isYmM5mJXzuGJu4/ey08T8kJaOcNNc2eWG3ijH9AYYgPUqn21ej6Vkr7HkE37cO8y8bSqfJokaIvg7vKvHX4uzYGWt+yPcQs7vaKLeCfO5vfcJXmX45GuTuHWqXk0HNl0O7jIoOhlBR/HNGx2P8D9ZzKE7/Lcr6lp/ymzyOI9qnAaxvg0837Y2G/kWJijYWwBVeHKe9hKbjd3VPkNobWrQtx1ZIzaed
    username: AgDLPE3ZxH0UN2mU03OQM93+wx3LteWzQSMa0OsFhd3s1v+PWmJVXdRGAMHf62d7B9S0Pn/qfPaj7i9+z+xaGQEXmGjkgBm8Kee5rZDTGFcIuSc9SlkqPTx0WNzu6HV6yGh1nNhjEBQ91405u69cRtQ3vM6TIOvd/oJanWTAVuElVavXkNHASl3+Gh4TDTB3b8GQaclEO674dfB1wR0ADhwOOhlG2aWdL85ktR2WcDduHmsIUeSbXUhH1NVEu5XX6KEYmjlt44u+OcMQcokuP6jZ1Azniz7WdiGSwfjFBW5MOW2H9lQ8qK4uFVW1kecey8mfRybaBHoeRD36B3R0N343cmimqnnHywjSXHqjL5xs9sZL+FnovrT19kjjdErdDKXbdq6xOeTYVsAt5T8ZrtdRr/edGcYHKP/UIOq3/63VyFKs7LAo7RHKkXPrXh1MfpO4eu692o/4tKuKhkeBTb2VavQc08Qx2MufIQ+5G0UB6Y7brRBc7SRvSP/TzBos2rbJhu4sBpwOe0cOPFbytVBQx96/8yy5d93l0a74AaxBXItHO8Q+sxgEEHtJ/B0764cYccvh9br0xfADPNgpKYPOBhWZTZ22NNkIxZeuxRicTcNiFwwZFk5LF1O0wHQ2G2kp6IOFT/DkA9eTuJiAiBlTiyx2u8K3eIc9qDPsf30Iz9xCmXNtSPyAhb7yNKyO7mB6c0lNZ4M=
  template:
    metadata:
      creationTimestamp: null
      name: gitea-db-secret
      namespace: database-infra
    type: kubernetes.io/basic-auth

