apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: sprint-build-pipeline
  namespace: sprint-build
spec:
  description: | 
    This pipeline clones a git repo, builds a Docker image with Kaniko and
    pushes it to a registry
  params:
  - name: repo-url
    type: string
  - name: repo-revision
    type: string
  - name: image-reference
    type: string
  - name: repo-full-name
    type: string
  - name: commit-id
    type: string
  workspaces:
  - name: shared-data
  - name: docker-credentials
  tasks:
  - name: gitea-set-status-cloning
    taskRef:
      name: gitea-set-status
    params:
    - name: REPO_FULL_NAME
      value: $(params.repo-full-name)
    - name: GITEA_HOST_URL
      value: code.sprint.luchtenberg.eu
    - name: SHA
      value: $(params.commit-id)
    - name: DESCRIPTION
      value: "Bezig met source code clonen"
    - name: STATE
      value: "pending"
    - name: TARGET_URL
      value: https://tekton/dashboard/taskrun/log
    - name: CONTEXT
      value: "Sprint-build-pipeline"
  - name: fetch-source
    runAfter: ["gitea-set-status-cloning"]
    taskRef:
      name: git-clone
    workspaces:
    - name: output
      workspace: shared-data
    params:
    - name: url
      value: $(params.repo-url)
    - name: revision
      value: $(params.repo-revision)
  - name: gitea-set-status-building
    runAfter: ["fetch-source"]
    taskRef:
      name: gitea-set-status
    params:
    - name: REPO_FULL_NAME
      value: $(params.repo-full-name)
    - name: GITEA_HOST_URL
      value: code.sprint.luchtenberg.eu
    - name: SHA
      value: $(params.commit-id)
    - name: DESCRIPTION
      value: "Bezig met Image bouwen"
    - name: STATE
      value: "pending"
    - name: TARGET_URL
      value: https://tekton/dashboard/taskrun/log
    - name: CONTEXT
      value: "Sprint-build-pipeline"
  - name: build-push
    runAfter: ["gitea-set-status-building"]
    taskRef:
      name: kaniko
    workspaces:
    - name: source
      workspace: shared-data
    - name: dockerconfig
      workspace: docker-credentials
    params:
    - name: IMAGE
      value: $(params.image-reference)
  - name: gitea-set-status-complete
    runAfter: ["build-push"]
    taskRef:
      name: gitea-set-status
    params:
    - name: REPO_FULL_NAME
      value: $(params.repo-full-name)
    - name: GITEA_HOST_URL
      value: code.sprint.luchtenberg.eu
    - name: SHA
      value: $(params.commit-id)
    - name: DESCRIPTION
      value: "Je image is klaar en naar $(params.image-reference) gepushed"
    - name: STATE
      value: "success"
    - name: TARGET_URL
      value: https://tekton/dashboard/taskrun/log
    - name: CONTEXT
      value: "Sprint-build-pipeline"
    