apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  name: sprint-build-triggertemplate
  namespace: sprint-build
spec:
  params:
    - name: repo-revision
      description: The git revision
      default: master
    - name: repo-url
      description: The git repository url
    - name: repo-full-name
      description: Full name of git repo
    - name: commit-id
      description: Commit id
    - name: image-reference
      description: Target image registry
  resourcetemplates:
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        generateName: sprint-build-
        namespace: sprint-build
      spec:
        pipelineRef:
          name: sprint-build-pipeline
        podTemplate:
          securityContext:
            fsGroup: 65532
        workspaces:
        - name: shared-data
          volumeClaimTemplate:
            spec:
              storageClassName: local-path
              accessModes:
              - ReadWriteOnce
              resources:
                requests:
                  storage: 1Gi
        - name: docker-credentials
          secret:
            secretName: docker-credentials
        params:
        - name: repo-url
          value: $(tt.params.repo-url)
        - name: repo-revision
          value: $(tt.params.repo-revision)
        - name: image-reference
          value: $(tt.params.image-reference)
        - name: repo-full-name
          value: $(tt.params.repo-full-name)
        - name: commit-id
          value: $(tt.params.commit-id)
---
apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerBinding
metadata:
  name: sprint-build-pipelinebinding
  namespace: sprint-build
spec:
  params:
    - name: repo-revision
      value: $(body.ref)
    - name: repo-full-name
      value: $(body.repository.full_name)
    - name: commit-id
      value: $(body.after)
    - name: repo-url
      value: "https://code.sprint.luchtenberg.eu/$(body.repository.full_name)"
    - name: image-reference
      value: "code.sprint.luchtenberg.eu/microservices/$(body.repository.name):latest"
---
apiVersion: triggers.tekton.dev/v1beta1
kind: EventListener
metadata:
  name: sprint-build-listener
  namespace: sprint-build
spec:
  serviceAccountName: tekton-triggers-example-sa
  triggers:
    - bindings:
      - ref: sprint-build-pipelinebinding
      template:
        ref: sprint-build-triggertemplate

