apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: webhook-secret
  namespace: sprint-build
spec:
  encryptedData:
    secret: AgBYUT+2wof7szr1NZ0zqcBefF/tenkNgZhslLUBCZ217mYeOzz78ToggJf4jkirKLz1w8sgbamEnE4QCVhUn++gnWm77xvgNeQ5ZhVGFWUndALqhQ757ISJFE3vs5OrJRtaQXic9+jh+MJJvJwNYMPpN4Y2ezA3fik/JwdwKQQq2q141oknRrSWj0/rqT/afxIpIhj21N0hX6u3mGo8Wquw6AoxcC/NCMH26ixGBKMXKQPgLPBaO61pI/V3tbRGe0XYBmit43wiicStnCNb6rDAnnr2aEzx5Q6fEc7N8Y1DWKkhv7r0TCZbMGOGrFXiSQo7afnErq/aGN4If+Qjss9E/7WdAlWhTs0XXw4kIXpax/3HnTTYgJqvOiNng3Sw7hvFw51wy+B+4vfehnHhf1dBU4Eiw3i4wr6gU3ADqpbKea61AUfxud+pT9jKoxVYBqDA1oGgCMOTy2YE5Rk9EhzUlbTfd4dxb13PmBTVeoeDc32DsUXPdn48G4kgGREZecp9eUSHL5JRlSHM+F2VwxeqRlK6BIasv1J6y60HcCYtt7FLQKTlW1fNGwVF2pnwOSO9PXpLE+jI2z//BI8hqk5BGYctORCKfH5n7Lk/cDeJUfoooEqufdm7cMcnptTHZevkT97gphytAAiUNAPEylI6FAqnS7JoC0yM69lKQ8/5ar2MK5hRPYlvvTowmOUp75nZP0aFDqYu3q3gpDdVJ9oBmj8=
    token: AgCzCgwsHCsUEQMvFz9oqswAVjCv3Ft/Pd9f4G0z8Gqi63P6xY1PSYnKuvu0JRMSQlP/O32AUfypXPB0sfV7WCaFN2KtBBhA/r31dxyGGEHLxcGfQZPxsmBY84aan9EcStBxfx9fK7dJTgVDObmNtkVbDTSD+Jc0/IvINtW5sARAWWqaNFqhakFLaJag7lJlvWdEHMATa17otNubgKVx6shHu5EyQ/XgcFYQsSsheT+3f9nLxrIdqj/WoWnMSKirhFxqwkaVx8yLTE5czVYGrflPVRLzR11rlYfLDijXaXTQFxLOcGwAvjc+32V/KhyXl6rGWXjMCZ4cfiRSl0cYeqbitTL4gJ49D0OO9WcI7Mf3rw2xlBIisE4yRcduOuXLddc+00Lu/9GqhvAvGggDFYFpvA4nIcJhyND2aSia/cHNfJPAQLTdTxsDw/kbsDya94qKanPBFlRajeCoFkaKLzAKLxzbaBU0eYeil897y9YNtP06vLJNYQgpdzkHdTzAq8GR5Z7b4OXH+ticiPZRsTBW/YwIuu7mPpnyBSpwOevCALaQM0Jqfki/p/ic25wGiVkqqhr8z7FAgpVzfbHTOgnygt8nDOX3eo6WV5vU8HkMmrlRsmu2noYVDxC9BCKrLlP/Gt/OuIPzh1nFyo1pWnHlRmmvOs97t0SLirum6/eDSbLo9xF2l5BVbDCC4pvwH9rMpCTbOuYll7QdUf66LvltjIqcgtKbntRwG+AVNKJEFLqswTw1pMsBOqT+iImbZOM7KVDCOe6CXLMoeLouiC0NyxxQLsc/m7RQGxWdU26nJ0KiZsUO8uMtEgWjcCQ=
  template:
    metadata:
      creationTimestamp: null
      name: webhook-secret
      namespace: sprint-build

