apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: kaniko-build-
  namespace: sprint-pipelines
spec:
  pipelineRef:
    name: kaniko-build
  podTemplate:
    securityContext:
      fsGroup: 65532
  workspaces:
  - name: shared-data
    volumeClaimTemplate:
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
  - name: docker-credentials
    secret:
      secretName: docker-credentials
  params:
  - name: repo-url
    value: https://github.com/google/docsy-example.git
  - name: image-reference
    value: private-repo.private-repo.svc.cluster.local:5000/sprint-cloud:0.1