commonLabels:
  environment: staging

bases:
  - "../../base"

patchesStrategicMerge:
  - patch-cert.yaml

patches:
  - patch: |
      - op: replace
        path: '/spec/routes/0/match'
        value: Host(`longhorn.infra.sprint.luchtenberg.eu`)
    target:
      kind: IngressRoute
      name: longhorn
