apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: longhorn
  namespace: longhorn-system
spec:
  commonName: "longhorn.infra.sprint.luchtenberg.eu"
  dnsNames:
    - "longhorn.infra.sprint.luchtenberg.eu"