apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: longhorn
  namespace: longhorn-system
spec:
  routes:
  - kind: Rule
    match: Host(`longhorn.infra.sprint.luchtenberg.eu`)