apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: docker-credentials
  namespace: default
spec:
  encryptedData:
    config.json: AgBeq4L6KV64XiYSpD4KWbJ3wvINtfJIfZx+ZlhZYVc1V2KtEzPJ1QccvU6fvKaNmcwMUD7+sAwwyW7BX1jXYjgUeeLzUt80ag1ztC0Ab1LiugpDjV0k9KO1z9vPX8E0SM1Z+Jfwf4SECUNlixR+woMdOxCBypQ+q03EbrD4TIBzXY3nf+upPaH3Lx7km691xnKxVl7Zl67oJkRIU6IxvIvCNZpIp4Dya0W5/1p1BE9jmu+wA1Grh7keOXWS5ieestVnA/89sQlTUBzsE0Gk2Fw9fS0ksdApShftKFnKcsdf0nro3RgKWk5GwYhW0Kh4oQNwrE4tDDxh/ivHXrNJVwUgt4Pkt75aJDIpqryLh/SGqTv/RFtcE9jeOEkJkGcNi1a+CcdjipS3r3T7MhDFQxmx7jeG73DQUrPv4qG69N3Za5EfG8sJ8AqyGZSipG1B+t3EDGyqQCah9UlCtUSSR5/G2zy9UAEECPOCxqY8UAqQgfl6p4b5G16gjLTqlaEXhuJ/f+X1ZjGwQy6ev55IjTei1Rk7mRzm1orbaXiM99HzNV45pot2hKIwzXeRmSYK1GyNxHqrf9MEbHGoFJlYB01+wu/W3bgJ5m08nOXzLgDuGIPbMs+gp46CrCquFMlOGMH/bPg9N1SxcLLNU1RlzhoQBSnUYDK2A5DbQ+2QSfDsLp6ke5TkCIswHTR7BmGugTagXVpGHBiVVAlT4Bk8LSuAFkBo+T7woKpAMKP+6ZqQxJUi4gv9hIWWWA7E+Try9rHp6EtDcJK30OGOKVhVUYSb9AvtZ6y27vlcfTp22LOd/N6TGrvsTBT9gZi0e4Z6FgMUAhI5fB4=
  template:
    metadata:
      creationTimestamp: null
      name: docker-credentials
      namespace: default

