apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vcluster-test
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  project: vclusters
  destination:
    namespace: vcluster-test-cluster
    name: in-cluster
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
  source:
    repoURL: 'https://charts.loft.sh'
    targetRevision: 0.14.0
    chart: vcluster
    helm:
      values: |
        vcluster:
          image: rancher/k3s:v1.23.5-k3s1  