apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: knative-serving
commonLabels:
  team: infrastructure
resources:
  - namespace.yaml
  - knative-serving.yaml
  - https://github.com/knative-sandbox/net-certmanager/releases/download/knative-v1.8.1/release.yaml