apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: standard-vcluster-db
spec:
  instances: 3
  primaryUpdateStrategy: unsupervised
  monitoring:
    enablePodMonitor: true
  storage:
    storageClass: local-path
    size: 10Gi
  bootstrap:
    initdb:
      database: vcluster
      owner: vcluster