apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: sprint-staging
  namespace: knative-serving
  annotations:
    kubernetes.io/ingress.class: traefik-external
spec:
    entryPoints:
      - websecure
    routes: 
      - match: HostRegexp(`{subdomain:(.*)}.staging.apps.sprint.luchtenberg.eu`)
        kind: Rule
        services:
          - name: kourier-internal
            port: 80
    tls:
      secretName: staging-apps-sprint-luchtenberg-eu-tls
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: staging-apps-sprint-luchtenberg-eu
  namespace: knative-serving
spec:
  secretName: staging-apps-sprint-luchtenberg-eu-tls
  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer
  commonName: "*.staging.apps.sprint.luchtenberg.eu"
  dnsNames:
    - "*.staging.apps.sprint.luchtenberg.eu"
