bases:
  - ../../base

resources:
  - gitea-admin-secret-sealed.yaml
  - inline-config-sealed.yaml

patches:
  - patch: |
      - op: replace
        path: '/spec/routes/0/match'
        value: Host(`code.sprint.luchtenberg.eu`)
    target:
      kind: IngressRoute
      name: gitea
  - patch: |
      - op: replace
        path: /spec/issuerRef/name
        value: letsencrypt-staging
    target:
      kind: Certificate
      name: gitea-cert
  - patch: |
      - op: replace
        path: /spec/commonName
        value: code.sprint.luchtenberg.eu
      - op: replace
        path: /spec/dnsNames
        value: ['code.sprint.luchtenberg.eu']
    target:
      kind: Certificate
      name: gitea-cert
