apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://charts.jetstack.io
    targetRevision: "v1.10.1"
    chart: cert-manager
    helm:
      values: |
        installCRDs: true
        replicaCount: 3
        extraArgs:
          - --dns01-recursive-nameservers=1.1.1.1:53,9.9.9.9:53
          - --dns01-recursive-nameservers-only
        podDnsPolicy: None
        podDnsConfig:
          nameservers:
            - "1.1.1.1"
            - "9.9.9.9"

  destination:
    name: in-cluster
    namespace: cert-manager
  syncPolicy:
    syncOptions:
      - CreateNamespace=true