apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: docker-registry
  namespace: argocd
spec:
  destination:
    namespace: docker-registry
    server: https://kubernetes.default.svc
  project: default
  source:
    path: docker-registry
    repoURL: https://github.com/sprint-cloud/k8s-infra
    targetRevision: HEAD
