apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: knative-serving
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'https://github.com/sprint-cloud/k8s-infra'
    path: knative-serving/overlay/staging
    targetRevision: HEAD
  destination:
    server: 'https://kubernetes.default.svc'
  ignoreDifferences:
    - group: 
      kind: Namespace
      jsonPointers:
        - /metadata/labels
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
