apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: knative
  namespace: argocd
spec:
  project: infrastructure
  source:
    repoURL: 'https://github.com/sprint-cloud/k8s-infra'
    path: knative
    targetRevision: HEAD
  destination:
    server: 'https://kubernetes.default.svc'
  ignoreDifferences:
    - group: 
      kind: Namespace
      jsonPointers:
        - /metadata/labels
