apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus-stack
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    targetRevision: "44.2.0"
    chart: kube-prometheus-stack
    helm:
      skipCrds: true
      values: |
        defaultRules:
          create: true
          rules:
            alertmanager: false
            etcd: false
            configReloaders: false
            general: false
            k8s: true
            kubeApiserver: false
            kubeApiserverAvailability: false
            kubeApiserverSlos: false
            kubelet: true
            kubeProxy: false
            kubePrometheusGeneral: false
            kubePrometheusNodeRecording: false
            kubernetesApps: false
            kubernetesResources: false
            kubernetesStorage: false
            kubernetesSystem: false
            kubeScheduler: false
            kubeStateMetrics: false
            network: false
            node: true
            nodeExporterAlerting: false
            nodeExporterRecording: true
            prometheus: false
            prometheusOperator: false
  
        alertmanager:
          enabled: true
          alertmanagerSpec:
            storage:
              volumeClaimTemplate:
                spec:
                  storageClassName: local-path
                  accessModes: ["ReadWriteOnce"]
                  resources:
                    requests:
                      storage: 5Gi
        prometheus:
          enabled: true
          prometheusSpec:
            retention: 5d
            retentionSize: 49Gi
            podMonitorSelectorNilUsesHelmValues: false
            ruleSelectorNilUsesHelmValues: false
            serviceMonitorSelectorNilUsesHelmValues: false
            probeSelectorNilUsesHelmValues: false
            storageSpec:
              volumeClaimTemplate:
                spec:
                  storageClassName: local-path
                  accessModes: ["ReadWriteOnce"]
                  resources:
                    requests:
                      storage: 50Gi
        grafana:
          enabled: true
          defaultDashboardsTimezone: Europe/Amsterdam
          adminPassword: prom-operator
          sidecar:
            dashboards:
              enabled: true


  destination:
    name: in-cluster
    namespace: metrics
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true