apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: shipwright
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/sprint-cloud/k8s-infra'
    path: shipwright
    targetRevision: HEAD
  destination:
    server: 'https://kubernetes.default.svc'