apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sprint-build
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  project: default
  source:
    repoURL: 'https://github.com/sprint-cloud/k8s-infra'
    path: sprint-build/overlays/staging
    targetRevision: HEAD
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: sprint-build
  syncPolicy:
    automated:
      selfHeal: true
      prune: true