apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tekton
  namespace: argocd
spec:
  project: infrastructure
  source:
    repoURL: 'https://github.com/sprint-cloud/k8s-infra'
    path: tekton
    targetRevision: HEAD
  destination:
    server: 'https://kubernetes.default.svc'