apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: argocd
  namespace: argocd
spec:
  commonName: "argocd.infra.sprint.luchtenberg.eu"
  dnsNames:
    - "argocd.infra.sprint.luchtenberg.eu"