apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: argocd-server
  namespace: argocd
spec:
    routes: 
      - match: Host(`argocd.infra.sprint.luchtenberg.eu`)
        kind: Rule