apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: gitea
spec:
  instances: 3
  primaryUpdateStrategy: unsupervised
  bootstrap:
    initdb:
      database: gitea
      owner: gitea
      secret:
        name: gitea-db-secret
  monitoring:
    enablePodMonitor: true
  storage:
    storageClass: local-path
    size: 10Gi