apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-api-token-secret
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgBeuNUML6oGwoDYpOypr0ZEdcw/ouzlwWWvBjPQWyJTjzWm3v3GTalavmTpVrN9uECLvu02I7goV6zpd3mUMr6c/SjK/G9mi5qQbJ0tku1kayBrechqfwm4hk9KKK11J8hOEfLfcwoHe26FErr9pg8TBiQjXL64uez57D4MEJIUZY22qD7/QhgN7ZQlOadnaal/Apf4nm4GwemFm5EWNaIfGNyzPNTUMe8I8LlBdufAzzsEEgoFTALqbNYGB0m0L/5U7H4KIV9ZX9p2dOfqRfFiquX8ohq9jBcBXzZxJdSKBt4UOHGrSLFqbD9tVDRo0IaY2h6KWMRnlQmsDMOoVkEnh2IqGyjIvmF943m1jr4XxleK9rf87w2tKZJTDr2eS3fMI84oFzuMWuzgwV/r7VWa+y10CiVZhDaUwSH3MKbZdAXz6PGYDB4Lx2kJnoPBiNpvFDiEZ2Mdn1JnfKPeGOHSkOWfhsM+pxk9RtC9dH4jHb59UNtb5P7OOZAOxt+eR/GWqW2ojp3zEf0LSSBPZvVjOv0++jDzLGhUu6pKEsVnJKgEqpD1rAndmiS0qR545J4Tq2tOj8zVy+qCxTym/LnzpZEU8AD/6ATHw/akO7KqBDC78aGPODRKgCPsERr8vFAnTLjvoF6Z2hHwJ3X/nGZCiHaECzk7DALqpVzWJnfjOfvHN0LuCANmYZFVDv7EQTwcrYQ/KzL+XjxR9pdOiQrOhSCn1jc20PpfSSZ5HeYS1WzReWF/jKU8
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-api-token-secret
      namespace: cert-manager
    type: Opaque

