apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-api-token-secret
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgAQnqisJ+/qtaACCyyoPPu8zpdcu8upj37wq/XZYDK+7siKCNSdvUiHNMn27Izk+AEynwGd4UvnMK2jF3Vtdw+bArQZSEFQSQTymKZFz2W/YecPeonlsOxDB0g7rxF+GpTPmgLwmRLrjhs7BSnOMw0ajElCBR+zWxt5tft4nem5B19dqcLUx2W/29Q8e5nHcU0qEKE6PxK7jWnAzPws+jLITvvSTO/Gn8L1y8ccWeHVJRJS3oYDj7yDx3hhdxJ2qtchui0DyFl3ySVdXUaIB55dI+xNqvPBF+QZ51ANAqdhGwCof+X3Wtr4Ody9rQAg/tu1H00fRCgHawNScFiV2P4nwippiRGAXCJX5SXOdABoF//URXS5SKgrJMeDYXABuHpLgbNBI9H3qd2Y57FS+9pFPhI1tV66jlfDS2tnShDky3hWyCgg6zKlJLbmrJxPuV1lKzfdP/ZCgyHzWXzv4+6Ae0F7wphFEw+FdcwO0xnkwCSoIE4YeKmEf/INHmQf0e6i+4mKB2aD1p4trveByEYcrSdBujP67rgrasicV65iPwzcYVJHXfCTmVSTY2Vakd7C0VrO+GJaCTDVPV/qe1odLI6izTSSCpIIgd7iB55BxJ23PNB1wgRg85Msq14Pg20MwwDi76u+LrOON6n6UAoyHgAhgFgV3h9qmoeeYCSDPVZLC5ybsqv8F7HSUf89UA5vn5qaJ3zfG6BSC+ggLrvlLDmhRntR6/c44Tfn9giU0ng1lx8hwMBr
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-api-token-secret
      namespace: cert-manager
    type: Opaque

