apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-api-token-secret
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgBZAr5DFo6JEt+UaCqrNsy4QMpaeq4WcNMpz6Z3J+2n/2Qc/T+vS8Vc2sZqYDDPc22WtvxNUYnek/cMr6rm6fOl4vcarXGjLmBgNRqnJs7CB6sXwTlytX6QJGfZ26pe+gnppI28lWPvjQCT49ORxTIgeHnb86Wnj+IGuJsdskIKDryIjV6FYtX6J0zrIBxHmL6Xu/OxCjx+kpoXQY6CC8AP03w1x5eZYSa8uqpaaWpUhL5mtv6yECzYkSCdJBgcGRKAXxqNYJKl5JC4T4afffJw/SH2Nz5dmxfRYtlQ7v7YG2CUuNTfa2GxhuiFcEOmhJ8B31mobjqZ2d2ZlfboqhdnLubo+KmFxJQQ8WPXN3rHoHUO6xA58P/F1UpRSz+lGqeiCiIPFrwAgcBNG1iatzTJss//tmhRtKvCyZNpZStPnOmhS+yM1ZOjhSmk1V7spwY6OOAHOpISwteh3069a1uwOYmdsUYjr3Gw/5+WYbc4xGgw8+cjgoLRRuAre74izKrJVNwIjlneY4EDg6dDEPYrG3KAL7GJHgB7S5sgH0WW6iQdeBYpR9Stn1Ox/RYiLGgkxCrZMLITlmxbllaXAzlDhZ+6psiIkIkH+rZl6vVIjGyTJQHzyOjCvFLNK6twx+GFxlNUqME0jOKkYwLutEWrhlsFwPAHapeH6mLsUJ92srPN6cjfeoyAV02ny5DbB9KALRUjUYUtONvJ5LTbOrYWEqOznk+bLVHQY+/5XExq9nQXfb7w/LeU
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-api-token-secret
      namespace: cert-manager

