apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus-crds
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: sprint-services
  source:
    repoURL: https://github.com/prometheus-community/helm-charts.git
    targetRevision: "kube-prometheus-stack-44.2.0"
    path: charts/kube-prometheus-stack/crds
    directory:
      recurse: true
  destination:
    name: in-cluster
    namespace: metrics
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - Replace=true
    automated:
      selfHeal: true
      prune: true