apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus-stack
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: sprint-services
  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    targetRevision: "44.2.0"
    chart: kube-prometheus-stack
    helm:
      skipCrds: true
      values: |
        alertmanager:
          enabled: true
          alertmanagerSpec:
            storage:
              volumeClaimTemplate:
                spec:
                  storageClassName: longhorn
                  accessModes: ["ReadWriteOnce"]
                  resources:
                    requests:
                      storage: 2Gi
        prometheus:
          enabled: true
          prometheusSpec:
            podMonitorSelector:
              matchLabels:
                metrics: enabled
            retention: 5d
            retentionSize: 50GB
            storageSpec:
              volumeClaimTemplate:
                spec:
                  storageClassName: longhorn
                  accessModes: ["ReadWriteOnce"]
                  resources:
                    requests:
                      storage: 51Gi
        grafana:
          enabled: true
          defaultDashboardsTimezone: Europe/Amsterdam
          adminPassword: prom-operator
          sidecar:
            dashboards:
              enabled: true
  destination:
    name: in-cluster
    namespace: metrics
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true